meta_name: "FRS-One"
meta_title: "FRS-One - Fire safety compliance solution"
meta_description: "FRS-One provides you with digital solutions to comply with fire safety regulations"
meta_image: "Flare-share.png" # should exist in `app/assets/images/`
twitter_account: "@killian15450712"   # required for Twitter Cards
