meta_name: "Flare Risk"
meta_title: "Flare Risk - Fire safety compliance solution"
meta_description: "Flare Risk provides you with digital solutions to comply with fire safety regulations"
meta_image: "flare-logo.png" # should exist in `app/assets/images/`
twitter_account: "@killian15450712"   # required for Twitter Cards
